pollingIntervalMs: 10000

# Chain configurations
chains:
  - name: "Optimism Sepolia"
    chainId: 11155420
    rpcUrl: "https://sepolia.optimism.io"
  - name: "Base Sepolia"
    chainId: 84532
    rpcUrl: "https://sepolia.base.org"

# Relay pairs to monitor
relayPairs:
  - sourceChainId: 11155420
    sourceResolverAddress: "0x19d69402f218b9997a904648d71f22be8a8bfb4a"
    destChainId: 84532
    destDappAddress: "0x96ebfae22b549beecdf50f9adc0850fb548a69fc"

polymerApi:
  endpoint: "https://proof.testnet.polymer.zone"
